setwd("C:/Users/Jennifer/Desktop/DATA ANALYSIS/GETTING AND CLEANING DATA/Course project")
trainX=read.csv("X_train.csv", header=FALSE)
trainY=read.table("y_train.txt", header=FALSE, sep=" ")
trainS=read.table("subject_train.txt", header=FALSE, sep=" ")
trainset=cbind(trainS,trainY,trainX)
testX=read.csv("X_test.csv", header=FALSE)
testY=read.table("y_test.txt", header=FALSE, sep=" ")
testS=read.table("subject_test.txt", header=FALSE, sep=" ")
testset=cbind(testS,testY,testX)
dataset=rbind(trainset,testset)
dataset[,2]=as.factor(dataset[,2])
levels(dataset[,2])=c("WALKING","WALKING_UPSTAIRS","WALKING_DOWNSTAIR","SITTING","STANDING","LAYING")
measurementnames=read.table("features.txt",header=FALSE)
vector=as.vector(measurementnames[,2])
colnames(dataset)=c("Subject","Activity",vector)
write.csv(dataset,"tidydata.csv")
